# fly.toml file for Freight Broker API deployment on Fly.io

app = "freight-broker-happyrobot"
primary_region = "iad"

[build]
  dockerfile = "DockerFile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    method = "get" 
    path = "/"
    protocol = "http"
    timeout = "10s"
    grace_period = "5s"

[env]
  PYTHONPATH = "/app"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "python init_db.py"
